export const testimonials = [
  {
    image: "https://cdn.marvel.com/content/1x/echo_0109_com_mas_dsk_01.jpg",
    title: "Echo now Streaming",
    text: "STREAM ON HULU",
    link: "https://www.daum.net",
    imgLogo: "https://cdn.marvel.com/content/1x/echo_lob_log_eye_01_0.png",
    logoMax: 175,
    imgTit: "STREAM THE 5-EPISODE EVENT NOW!",
    imgNote: "Get Hulu, Disney+, and ESPN+, all with ads, for $14.99/mo",
  },
  {
    image: "https://cdn.marvel.com/content/1x/stormmagneto_com_mas_dsk_01.jpg",
    title: "The Weeks New comics",
    text: "SEE MORE",
    link: "https://www.daum.net",
    imgLogo: "https://cdn.marvel.com/content/1x/echo_lob_log_eye_01_0.png",
    logoMax: 175,
    imgTit: "This Week's New Comics",
    imgNote: "Join Storm's search for Magneto, behold the battle for Beast's soul, see Spider-Woman strike back in 'Gang War,' and more in this week's comics!",
  },
  {
    image: "https://cdn.marvel.com/content/1x/watchers9days_com_mas_dsk_01.jpg",
    title: "What if...? Season.2",
    text: "UNLOCK NOW",
    link: "https://www.daum.net",
    imgLogo: "https://cdn.marvel.com/content/1x/whatifs2_log_eye_02.png",
    logoMax: 208,
    imgTit: "The Watcher's Nine Days of What If...?",
    imgNote: "Check back each day at 9am PST for new reveals and exclusive gifts as we watch Season 2 of Marvel Studios’ What If…? Now streaming on Disney+.",
  },
  {
    image: "https://cdn.marvel.com/content/1x/echo_mu_com_mas_dsk_01.jpg",
    title: "Echo Comics to Read",
    text: "READ MORE",
    link: "https://www.daum.net",
    imgLogo: "https://cdn.marvel.com/content/1x/mulogo_lob_log_eye_01_1.png",
    logoMax: 70,
    imgTit: "Echo Comics to Read",
    imgNote: "Read our Echo comic picks on Marvel Unlimited ahead of the series premiere on January 10!",
  },
  {
    image: "https://cdn.marvel.com/content/1x/marvelsblade_lob_mas_dsk_01.jpg",
    title: "Marvel Blade in Development",
    text: "WATCH NOW",
    link: "https://www.daum.net",
    imgLogo: "https://cdn.marvel.com/content/1x/marvelsblade_lob_log_eye_01.png",
    logoMax: 303,
    imgTit: "ANNOUNCEMENT TRAILER",
    imgNote: "Watch the Game Awards 2023 trailer for 'Marvel's Blade' now!",
  },
];
